# Generated by Django 3.0.2 on 2020-01-30 19:28

import app.gallery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the gallery.', max_length=1024, verbose_name='Name')),
                ('path', models.CharField(help_text='Path is used as url reference. It is generated automatically with creating new gallery', max_length=1024, verbose_name='Path')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp of last modification.', verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Representation of image in filesystem.', max_length=1024, upload_to=app.gallery.models.image_directory_path, verbose_name='Image file')),
                ('path', models.CharField(help_text='Name of the image file (e.g. elephant.jpg).', max_length=1024, verbose_name='Path')),
                ('name', models.CharField(help_text='Name of the image. It is generated from filename.', max_length=1024, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp of last modification.', verbose_name='Modified')),
                ('gallery', models.ForeignKey(help_text='Image belongs to gallery.', on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
