# Generated by Django 3.0.2 on 2020-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.SlugField(help_text='Path is used as url reference. It is generated automatically with creating new gallery', max_length=1024, verbose_name='Path'),
        ),
    ]
