# Generated by Django 3.0.2 on 2020-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200130_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the image. It is generated from filename.', max_length=1024, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(blank=True, help_text='Name of the image file (e.g. elephant.jpg).', max_length=1024, null=True, verbose_name='Path'),
        ),
    ]
