# Generated by Django 3.0.2 on 2020-01-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200130_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.SlugField(help_text='Path is used as url reference. It is generated automatically with creating new gallery', max_length=1024, unique=True, verbose_name='Path'),
        ),
    ]
