# Generated by Django 3.0.2 on 2020-01-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200131_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='path',
        ),
    ]
