# Generated by Django 3.0.2 on 2020-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_gallery_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(help_text='Name of the gallery. Must be unique.', max_length=1024, unique=True, verbose_name='Name'),
        ),
    ]
