# Generated by Django 3.0.2 on 2020-02-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200131_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Image height. It will be populated automatically.', null=True, verbose_name='Image height'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Image width. It will be populated automatically.', null=True, verbose_name='Image width'),
        ),
    ]
