# Generated by Django 3.0.2 on 2020-02-02 21:30

import app.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200202_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(height_field='height', help_text='Representation of image in filesystem.', max_length=1024, upload_to=app.gallery.models.image_directory_path, verbose_name='Image file', width_field='width'),
        ),
    ]
